### ISSUE TITLE
Make feed link optional

### ISSUE THREAD

**Issue by Ryuno-Ki** [alwayslivid/eleventy-about-me#4]
In your base template, you are currently always including a link to the feed.
However, it is possible that an user don't want to blog with eleventy. Thus, wrap it in an `{% if %}`.

**Comment by alwayslivid** [comment]
I was originally planning to add a blog feature to my template, but I've concluded that using this template for anything otherthan its original purpose is inefficient, as well as ugly.

However, I was planning to add a SEO feature that would allow people to define the canonical URL of their websites, but I seem to have temporarily removed the appropriate tag from the original source code. (See more [here](https://support.google.com/webmasters/answer/139066?hl=en))

I'm currently thinking about re-implementing that feature and leaving the source code as-is. I'd like to hear a secondary opinion on this, however.

**Comment by Ryuno-Ki** [comment]
If you would implement the link canonicalisation as an eleventy-plugin, that would be superb!
(Since I could use it as well).
Be aware, that it can become quite challenging! Think about variants (e.g. m-dot sites or print optimised) and internationalisation (different languages) as well as pagination (prev, next links?).

**Comment by alwayslivid** [comment]
> If you would implement the link canonicalisation as an eleventy-plugin, that would be superb!
> (Since I could use it as well).
> Be aware, that it can become quite challenging! Think about variants (e.g. m-dot sites or print optimised) and internationalisation (different languages) as well as pagination (prev, next links?).

I'm going to be honest– I probably won't be able to manage to pull this off.
